In [ ]:
install.packages('pracma')
require(pracma)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: pracma



In [ ]:
G = round(matrix(c(1,0,0,sqrt(2),0,1,sqrt(2),0,1,0,sqrt(2),0,0,1,0,sqrt(2)),4,4,),3)
round(G,1)
Rank(G)

[,1] [,2] [,3] [,4]
[1,] 1.0  0.0  1.0  0.0 
[2,] 0.0  1.0  0.0  1.0 
[3,] 0.0  1.4  1.4  0.0 
[4,] 1.4  0.0  0.0  1.4

[1] 3

In [ ]:
dec = svd(G)

In [ ]:
round(dec$u %*% (diag(dec$d) %*% t(dec$v)),2)

[,1] [,2] [,3] [,4]
[1,] 1.00 0.00 1.00 0.00
[2,] 0.00 1.00 0.00 1.00
[3,] 0.00 1.41 1.41 0.00
[4,] 1.41 0.00 0.00 1.41

In [ ]:
gtg = t(G)%*%G
ggt = G%*%t(G)

In [ ]:
round(dec$v %*% (diag(dec$d)^2 %*% t(dec$v)),3) # This gives gtg
round(gtg,3)

[,1]  [,2]  [,3]  [,4] 
[1,] 2.999 0.000 1.000 1.999
[2,] 0.000 2.999 1.999 1.000
[3,] 1.000 1.999 2.999 0.000
[4,] 1.999 1.000 0.000 2.999

[,1]  [,2]  [,3]  [,4] 
[1,] 2.999 0.000 1.000 1.999
[2,] 0.000 2.999 1.999 1.000
[3,] 1.000 1.999 2.999 0.000
[4,] 1.999 1.000 0.000 2.999

In [ ]:
round(dec$u %*% (diag(dec$d)^2 %*% t(dec$u)),3) # This gives ggt
round(ggt,3)

[,1]  [,2]  [,3]  [,4] 
[1,] 2.000 0.000 1.414 1.414
[2,] 0.000 2.000 1.414 1.414
[3,] 1.414 1.414 3.999 0.000
[4,] 1.414 1.414 0.000 3.999

[,1]  [,2]  [,3]  [,4] 
[1,] 2.000 0.000 1.414 1.414
[2,] 0.000 2.000 1.414 1.414
[3,] 1.414 1.414 3.999 0.000
[4,] 1.414 1.414 0.000 3.999

In [ ]:
gtgsvd = svd(gtg)
ggtsvd = svd(ggt)

gtgsvd$d <- ifelse(abs(svd(gtg)$d) <= 0.01, 0, svd(gtg)$d) # Getting the e-values greater than zero.
gtgsvd$d <- gtgsvd$d[ gtgsvd$d !=0]  # Second step in getting the e-values.

GtGU = gtgsvd$u[,1:length(gtgsvd$d)]
GGtU = ggtsvd$u[,1:length(gtgsvd$d)]

# 0   1   0   1
# 1   0   1   0
# 0   1.4 1.4 0
# 1.4 0   0   1.4

round(GGtU %*% (diag(sqrt(gtgsvd$d)) %*% t(GtGU)),2)

[,1] [,2] [,3] [,4]
[1,] 0.00 1.00 0.00 1.00
[2,] 1.00 0.00 1.00 0.00
[3,] 1.41 0.00 0.00 1.41
[4,] 0.00 1.41 1.41 0.00

In [ ]:
gtgsvd

$d
[1] 5.998792 3.998792 2.000000

$u
     [,1] [,2] [,3] [,4]
[1,] -0.5  0.5 -0.5 -0.5
[2,] -0.5 -0.5  0.5 -0.5
[3,] -0.5 -0.5 -0.5  0.5
[4,] -0.5  0.5  0.5  0.5

$v
     [,1] [,2] [,3] [,4]
[1,] -0.5  0.5 -0.5 -0.5
[2,] -0.5 -0.5  0.5 -0.5
[3,] -0.5 -0.5 -0.5  0.5
[4,] -0.5  0.5  0.5  0.5