In [ ]:
import numpy as np
%matplotlib inline

Conditions for ergodicity:

1. Irreducible:

In a Markov transition matrix $P$ with $N$ states all the entries in $$\sum_{n=0}^{N-1} P^n$$

must be $>0.$

2. Aperiodicity:

The paths from one state to itself are not only multiples of a period $T \geq 2.$ It can be checked by finding a loop in the transition diagram of $k$ steps, and another loop of $k+1$ steps. Once is enough if irreducible. With transition matrices: Find $k$ and $i$ such that $P^k_{ii}P^{k+1}_{ii}>0.$

3. Positive recurrence: If I am at a given state the expected time before returning to that state is finite. If the matrix is irreducible and the number of states is finite, it is a given.

In [ ]:
[0] * 3

[0, 0, 0]

In [ ]:
# Example: 1 -> 2 -> 3 -> 1

mat = np.array([
   [0,1,0],
   [0,0,1],
   [1,0,0],
])


# Irreducible:
matpow = [0] * 3
print(matpow)
for i in range(3):
 print(i)
 matpow = matpow +  np.linalg.matrix_power(mat,i)
 print(matpow)

matpow

[0, 0, 0]
0
[[1 0 0]
 [0 1 0]
 [0 0 1]]
1
[[1 1 0]
 [0 1 1]
 [1 0 1]]
2
[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Aperiodic:
# Example: 1 -> 2 -> 3 -> 1
# If we want to move from 1 to itself we can do it in 3 steps or 6 or 9 or 12... So it's periodic with T = 3.
print(np.linalg.matrix_power(mat,1))
print(np.linalg.matrix_power(mat,2))
print(np.linalg.matrix_power(mat,3))
# P to the power of 3 is the identity. Same for any P to the power of 1 + 3k or 2 + 3k or 3 + 3k.

[[0 1 0]
 [0 0 1]
 [1 0 0]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


A state i is an absorbing state if once the system reaches state $i,$ it stays in that state; that is, $\Pr_{ii}=1$.

### Non-ergodic chain with no absorbing state:

In [ ]:
Transition_matrix = np.array([
   [0,0.5,0,0.5,0],
   [0,0.5,0.5,0,0],
   [0,0.5,0.5,0,0],
   [0,0,0,0.5,0.5],
   [0,0,0,0.5,0.5],
])
N =100
Matrix_to_power_N = np.linalg.matrix_power(Transition_matrix,N)
Matrix_to_power_N

array([[0.  , 0.25, 0.25, 0.25, 0.25],
       [0.  , 0.5 , 0.5 , 0.  , 0.  ],
       [0.  , 0.5 , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.5 , 0.5 ],
       [0.  , 0.  , 0.  , 0.5 , 0.5 ]])

In [ ]:
# Check lack of irreducibility... number of states is 5:

N = 5

matpow = [0] * N
for i in range(N):
 matpow = matpow +  np.linalg.matrix_power(Transition_matrix,i)
matpow

array([[1.  , 1.25, 0.75, 1.25, 0.75],
       [0.  , 3.  , 2.  , 0.  , 0.  ],
       [0.  , 2.  , 3.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 3.  , 2.  ],
       [0.  , 0.  , 0.  , 2.  , 3.  ]])

### Non-ergodic chain with no absorbing state and each state with at least one incoming state:

In [ ]:
Transition_matrix = np.array([
   [0,0.5,0,0.5,0],
   [0,0.5,0.5,0,0],
   [0,0.5,0.5,0,0],
   [0,0,0,0.5,0.5],
   [0.1,0,0,0.4,0.5],
])
N =100
Matrix_to_power_N = np.linalg.matrix_power(Transition_matrix,N)
Matrix_to_power_N

array([[0.00214542, 0.47908182, 0.47798162, 0.01987296, 0.02091818],
       [0.        , 0.5       , 0.5       , 0.        , 0.        ],
       [0.        , 0.5       , 0.5       , 0.        , 0.        ],
       [0.00418364, 0.45920886, 0.45706344, 0.03875293, 0.04079114],
       [0.00397459, 0.46124707, 0.45920886, 0.03681655, 0.03875293]])

### Ergodic chain:

In [ ]:
Transition_matrix = np.array([
   [0,0.5,0,0.5,0],
   [0,0.5,0.5,0,0],
   [0.1,0.4,0.5,0,0],
   [0,0,0,0.5,0.5],
   [0.1,0,0,0.4,0.5],
])
N =100
Matrix_to_power_N = np.linalg.matrix_power(Transition_matrix,N)
Matrix_to_power_N

array([[0.04761905, 0.23809524, 0.23809524, 0.23809524, 0.23809524],
       [0.04761905, 0.23919864, 0.23932887, 0.23699184, 0.2368616 ],
       [0.04761905, 0.23908215, 0.23919864, 0.23710833, 0.23699184],
       [0.04761905, 0.23699184, 0.2368616 , 0.23919864, 0.23932887],
       [0.04761905, 0.23710833, 0.23699184, 0.23908215, 0.23919864]])