In [ ]:
# This function checks wheather a number (or vector of numbers) is (are) prime.

is.prime = function(x){
  prime = 1
  is.it.a.prime <- numeric(0)
  for(k in 1:length(x)){
  for(i in 2:ceiling(sqrt(x[k]))) ifelse(x[k] %% i == 0, prime <- 0, 1)
  if(x[k] == 2) prime <- 1
  is.it.a.prime[k] <- prime == 1
  }

rbind(number=x, is.it.a.prime)
}

In [ ]:
is.prime(c(113,19,137,7867,3167,6763,6762))

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
number        113  19   137  7867 3167 6763 6762
is.it.a.prime   1   1     1     1    1    1    0

In [ ]:
is.prime(7)

[,1]
number        7   
is.it.a.prime 1

In [ ]:
# Which numbers in a vector are prime:

prime.select = function(x){
  vec <- numeric(0)
  for(k in 1:length(x)){
  prime = TRUE
  for(i in 2:ceiling(sqrt(x[k]))) ifelse(x[k] %% i == 0, prime <- FALSE, prime)
  if(x[k] == 2) prime <- TRUE
  vec[k] <- prime
  }
  m = rbind(x, as.numeric(vec))
  m[1,m[2,]==1]
}

In [ ]:
prime.select(c(113,19,137,7867,3167,6763,6762))

[1]  113   19  137 7867 3167 6763

In [ ]:
prime.select(c(1:15))

[1]  2  3  5  7 11 13

In [ ]:
# Factoring into primes

factors = function(x){
  fact = numeric(0)
  i <- 0
  div <- 2
  rest <- x
  while(rest != 1){
    while(rest %% div == 0) {
      fact <- c(fact, div)
      rest <- rest / div
    }
    i <- i + 1
    div <- 2 * i + 1
  }
  fact
}

In [ ]:
factors(1985)

[1]   5 397

In [ ]:
factors(72)

[1] 2 2 2 3 3

In [ ]:
# Greatest common denominator:

gcd = function(a,b) {
    r <- a %% b
    while(r !=0 ){
      a <- b
      b <- r
      r <- a %% b
    }
    return(b)
  }

In [ ]:
# Modular inverse:

inverse.mod.m = function(a,m){
  if(gcd(a,m) != 1){
  paste('WARNING:', a, 'and', m, 'are not relatively prime. Hence,', a, 'has no inverse!')
  }else{
    mat <- matrix(0,0,4)
    x = m; w = a
    while(x%%w != 0){
    r <- x%%w
    mat <- rbind(mat, c(r, x, floor(x/w), w))
    x <- w; w <- r
    }

    mat[1,1] <- - mat[1,3] * sign(a)
    mat[2,1] <-  1 * (sign(a)) - mat[2,3] * mat[1,1]
    if(nrow(mat)>2){
    for(i in 3: (nrow(mat))){
            mat[i,1] <-  mat[i-2,1] - mat[i,3] * mat[i-1,1]
    }
        ans <- mat[nrow(mat),1]
    while(ans < 0)
    ans <- ans + m
    }else{
    ans <- 1*(sign(a)) - mat[2,3] * mat[1,1]
    }
    paste('The inverse of', a ,'is', ans, '(mod', m,')')
  }
}

In [ ]:
inverse.mod.m(-22,122)

[1] "WARNING: -22 and 122 are not relatively prime. Hence, -22 has no inverse!"

In [ ]:
inverse.mod.m(99,80)

[1] "The inverse of 99 is 59 (mod 80 )"

In [ ]:
inverse.mod.m(-21,122)

[1] "The inverse of -21 is 29 (mod 122 )"

In [ ]:
# Totient Euler function:

phi = function(n){
    result = 1
    for (i in 2:n)
        if (gcd(i, n) == 1)
            result = result + 1
    return(paste('There are ', result, ' relatively prime integers from 1 to', n, '.'))
}

In [ ]:
phi(16)

[1] "There are  8  relatively prime integers from 1 to 16 ."

In [ ]:
# Quadratic residues

quad = function(n){
    quad = numeric(0)
    for (i in 1: (n - 1))
      if(gcd(i,n)==1) quad <- c(quad, i^2 %% n)
    unique(quad)
}

In [ ]:
quad(7)

[1] 1 4 2

In [ ]:
# Legendre symbol

legend = function(a,m){
  quad = numeric(0)
  for(i in 1:(m-1)) quad <- c(quad, i^2 %% m)
  ifelse((a%%m) %in% quad, 1, -1)
}

In [ ]:
legend(34,13)

[1] -1

In [ ]:
# Finding primitive roots mod n:

primitive.roots.mod.n = function(n){

    phi = function(n){
    result = 1
    for (i in 2:n)
        if (gcd(i, n) == 1)
            result = result + 1
    return(result)
}

  print('WARNING: Loses accuracy above 17.')

  roots = numeric(0)
  for(i in 1:(n-1)){
    vec = numeric(0)
      for(k in 1:(n-1)){
          vec[k] <- i^k %% n
    }
    roots[i] <- length(unique(vec))
  }

  len = length(which(roots==phi(n)))
  r = which(roots==phi(n))
  m <- matrix(0, len, n - 1)
  for (k in 1: len){
          for (i in 1:(n - 1)) m[k, i] <- r[k]^i %% n
  }

l = list('primitive roots'=paste(list(which(roots==phi(n))), ' is/are primitive root(s) modulo', n, '.'), 'powers mod n'=m)
return(l)
}

In [ ]:
primitive.roots.mod.n(3)

[1] "WARNING: Loses accuracy above 17."


$`primitive roots`
[1] "2  is/are primitive root(s) modulo 3 ."

$`powers mod n`
     [,1] [,2]
[1,]    2    1

In [ ]:
primitive.roots.mod.n(5)

[1] "WARNING: Loses accuracy above 17."


$`primitive roots`
[1] "2:3  is/are primitive root(s) modulo 5 ."

$`powers mod n`
     [,1] [,2] [,3] [,4]
[1,]    2    4    3    1
[2,]    3    4    2    1

In [ ]:
primitive.roots.mod.n(7)

[1] "WARNING: Loses accuracy above 17."


$`primitive roots`
[1] "c(3, 5)  is/are primitive root(s) modulo 7 ."

$`powers mod n`
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    3    2    6    4    5    1
[2,]    5    4    6    2    3    1

In [ ]:
primitive.roots.mod.n(11)

[1] "WARNING: Loses accuracy above 17."


$`primitive roots`
[1] "c(2, 6, 7, 8)  is/are primitive root(s) modulo 11 ."

$`powers mod n`
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    2    4    8    5   10    9    7    3    6     1
[2,]    6    3    7    9   10    5    8    4    2     1
[3,]    7    5    2    3   10    4    6    9    8     1
[4,]    8    9    6    4   10    3    2    5    7     1

In [ ]:
primitive.roots.mod.n(13)

[1] "WARNING: Loses accuracy above 17."


$`primitive roots`
[1] "c(2, 6, 7, 11)  is/are primitive root(s) modulo 13 ."

$`powers mod n`
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
[1,]    2    4    8    3    6   12   11    9    5    10     7     1
[2,]    6   10    8    9    2   12    7    3    5     4    11     1
[3,]    7   10    5    9   11   12    6    3    8     4     2     1
[4,]   11    4    5    3    7   12    2    9    8    10     6     1