As a note to self (and hopefully some other people out there) I want to reflect here the comment by @Torsten Shoeneberg, which gives an immediate intuition as to how to build these matrices for any dimensions, and a perfect correspondence to the diagram:


$$\begin{align}
\small H&=\begin{bmatrix}\color{blue}4&0&0&0&0\\0&\color{blue}2&0&0&0\\0&0&\color{blue}0&0&0\\0&0&0&\color{blue}{-2}&0\\0&0&0&0&\color{blue}{-4}\end{bmatrix}\\
E&=\small \begin{bmatrix}0&\color{orange}4&0&0&0\\0&0&\color{orange}3&0&0\\0&0&0&\color{orange}2&0\\0&0&0&0&\color{orange}1\\0&0&0&0&0\end{bmatrix}\\
F&=\small \begin{bmatrix}0&0&0&0&0\\\color{lime}{1}&0&0&0&0\\0&\color{lime}{2}&0&0&0\\0&0&\color{lime}{3}&0&0\\0&0&0&\color{lime}{4}&0\end{bmatrix}
\end{align}
$$



For example $(0,0,0,1,0),$ corresponding to the fourth white dot, and performing the backet $[E,F].$ Starting with $EF,$

$F\cdot e_4=4 e_5$

and composing this result with $E,$ we obtain $4 e_4.$

Whereas $FE$ will entail starting with $E\cdot e_4 = 2 e_3$ which then becomes $2F\cdot e_3=6e_4$

In [ ]:
vec <- c(3+1i, -2-1i)

In [ ]:
H = matrix(c(4,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,-2,0,0,0,0,0,-4),5,5,1)
H
E = matrix(c(0,4,0,0,0,0,0,3,0,0,0,0,0,2,0,0,0,0,0,1,0,0,0,0,0),5,5,1)
E
F = matrix(c(0,0,0,0,0,1,0,0,0,0,0,2,0,0,0,0,0,3,0,0,0,0,0,4,0),5,5,1)
F

[,1] [,2] [,3] [,4] [,5]
[1,] 4    0    0     0    0  
[2,] 0    2    0     0    0  
[3,] 0    0    0     0    0  
[4,] 0    0    0    -2    0  
[5,] 0    0    0     0   -4

[,1] [,2] [,3] [,4] [,5]
[1,] 0    4    0    0    0   
[2,] 0    0    3    0    0   
[3,] 0    0    0    2    0   
[4,] 0    0    0    0    1   
[5,] 0    0    0    0    0

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0    0   
[2,] 1    0    0    0    0   
[3,] 0    2    0    0    0   
[4,] 0    0    3    0    0   
[5,] 0    0    0    4    0

In [ ]:
(H %*% E) - (E %*% H)
2 * E

[,1] [,2] [,3] [,4] [,5]
[1,] 0    8    0    0    0   
[2,] 0    0    6    0    0   
[3,] 0    0    0    4    0   
[4,] 0    0    0    0    2   
[5,] 0    0    0    0    0

[,1] [,2] [,3] [,4] [,5]
[1,] 0    8    0    0    0   
[2,] 0    0    6    0    0   
[3,] 0    0    0    4    0   
[4,] 0    0    0    0    2   
[5,] 0    0    0    0    0

In [ ]:
H %*% F - F %*% H
-2*F

[,1] [,2] [,3] [,4] [,5]
[1,]  0    0    0    0   0   
[2,] -2    0    0    0   0   
[3,]  0   -4    0    0   0   
[4,]  0    0   -6    0   0   
[5,]  0    0    0   -8   0

[,1] [,2] [,3] [,4] [,5]
[1,]  0    0    0    0   0   
[2,] -2    0    0    0   0   
[3,]  0   -4    0    0   0   
[4,]  0    0   -6    0   0   
[5,]  0    0    0   -8   0

In [ ]:
E %*% F - F %*% E
H

[,1] [,2] [,3] [,4] [,5]
[1,] 4    0    0     0    0  
[2,] 0    2    0     0    0  
[3,] 0    0    0     0    0  
[4,] 0    0    0    -2    0  
[5,] 0    0    0     0   -4

[,1] [,2] [,3] [,4] [,5]
[1,] 4    0    0     0    0  
[2,] 0    2    0     0    0  
[3,] 0    0    0     0    0  
[4,] 0    0    0    -2    0  
[5,] 0    0    0     0   -4