In [ ]:
!pip install silence_tensorflow
import silence_tensorflow.auto
import tensorflow as tf
import tensorflow_probability as tfp

  Created wheel for silence-tensorflow: filename=silence_tensorflow-1.1.1-py3-none-any.whl size=3743 sha256=bbc9a7a6177a4774fc7b4abb03f5149828e1f225d086fbef18c03f3f12b1d744
  Stored in directory: /root/.cache/pip/wheels/a2/42/cf/26148cd545b324903a62edde56cfc4502b278c104a07bb6b96
Successfully built silence-tensorflow


In [ ]:
def happiness_model():
  weather = yield tfp.distributions.JointDistributionCoroutine.Root(
      tfp.distributions.Bernoulli(probs=0.3, name="weather") # pobability of good weather.
  )
  weather_to_happiness = tf.constant([0.6,0.9]) # 60% happiness if bad weather; 90% if good weather.
  happiness = yield tfp.distributions.Bernoulli(
      probs= weather_to_happiness[weather], name="happiness"
  )

model_joint = tfp.distributions.JointDistributionCoroutineAutoBatched(happiness_model)

In [ ]:
model_joint.sample(10)

StructTuple(
  weather=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0], dtype=int32)>,
  happiness=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1], dtype=int32)>
)

In [ ]:
model_joint.prob([1,1]) # Pr good weather and good mood.

<tf.Tensor: shape=(), dtype=float32, numpy=0.27>

In [ ]:
0.3*0.9

0.27